services:
  - type: web
    name: plus-chat-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 # 使用したいバージョンに合わせて変更可
