services:
  # チャットAPIサーバーの設定
  - type: web
    name: plus-chat-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push && node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plus-chat-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Renderが自動で安全な文字列を作ってくれます
      - key: NODE_VERSION
        value: 18 # 使用するNodeのバージョンを指定

databases:
  # データベースの設定
  - name: chat-db
    plan: free
    region: singapore
    postgresMajorVersion: 15
